=== OpenST/Facilitator/src/m0_facilitator/Config/FacilitatorConfig.schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/Facilitator",
  "definitions": {
    "Address": {
      "type": "string",
      "pattern": "^0x[a-fA-F0-9]{40}$"
    },
    "Facilitator": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "originChain": {
          "type": "string",
          "additionalProperties": false
        },
        "auxChainId": {
          "type": "number",
          "additionalProperties": false
        },
        "database": {
          "$ref": "#/definitions/Database"
        },
        "chains": {
          "type": "object",
          "additionalProperties": false,
          "patternProperties": {
            "^.{1,50}$": {
              "$ref": "#/definitions/Chain"
            }
          }
        },
        "encryptedAccounts": {
          "$ref": "#/definitions/EncryptedAccounts"
        }
      },
      "required": [
        "chains",
        "database",
        "encryptedAccounts",
        "originChain"
      ],
      "title": "Facilitator",
      "description": "Object encapsulating details about facilitator config"
    },
    "Chain": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "worker": {
          "type": "string"
        },
        "nodeRpc": {
          "type": "string"
        },
        "subGraphWs":{
          "type": "string"
        },
        "subGraphRpc":{
          "type": "string"
        }
      },
      "required": [
        "worker",
        "nodeRpc",
        "subGraphWs",
        "subGraphRpc"
      ],
      "title": "Chain",
      "description": "It encapsulates chain specific information"
    },
    "Database": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "path": {
          "type": "string"
        }
      },
      "required": [
        "path"
      ],
      "title": "Database",
      "description": "It represents database config details"
    },
    "EncryptedAccounts": {
      "type": "object",
      "additionalProperties": false,
      "title": "EncryptedAccounts",
      "minProperties": 2,
      "maxProperties": 2,
      "patternProperties": {
        "^0x[a-fA-F0-9]{40}$": {
          "$ref": "#/definitions/Account",
          "description": "Represents encrypted account for an address"
        }
      },
      "description": "List of encrypted accounts"
    },
    "Account": {
      "type": "object",
      "title": "Web3 encrypted account",
      "description": "Object represents encrypted web3 account"
    }
  }
}

=== OpenST/Facilitator/test/m0_facilitator/FacilitatorConfig/testdata/facilitator-config.json
{
  "originChain":"dev-origin",
  "auxChainId":1000,
  "database": {
    "path": "/Users/gulshanvasnani/.mosaic/1000/facilitator/OSTFacilitator.db"
  },
  "chains": {
    "1000": {
      "worker": "0x81Df1244dEd6EF44a90a67526E4Ec4497d807F96",
      "nodeRpc": "https://localhost.com:8645",
      "subGraphWs":"ws://localhost:8000/subgraphs/name/openst/ost-composer",
      "subGraphRpc":"http://localhost:8000/subgraphs/name/openst/ost-composer"
    },
    "dev-origin": {
      "worker": "0xac7E36b3cdDb14Bf1c67dC21fFB24C73d03d8FF7",
      "nodeRpc": "https://localhost.com:8545",
      "subGraphWs":"ws://localhost:8000/subgraphs/name/openst/ost-composer",
      "subGraphRpc":"http://localhost:8000/subgraphs/name/openst/ost-composer"
    }
  },
  "encryptedAccounts": {
    "0xac7E36b3cdDb14Bf1c67dC21fFB24C73d03d8FF7": {
      "version": 3,
      "id": "b4c08520-2478-495f-a73e-12582c9629aa",
      "address": "ac7e36b3cddb14bf1c67dc21ffb24c73d03d8ff7",
      "crypto": {
        "ciphertext": "246dc793922c46974839ec62325c5f1f19233eacfcd6f5ab840a7cb6b715ccee",
        "cipherparams": {
          "iv": "144f7dcec03658a3a59695b9d547df26"
        },
        "cipher": "aes-128-ctr",
        "kdf": "scrypt",
        "kdfparams": {
          "dklen": 32,
          "salt": "0996b6398b2dd5fbabce76ce28437a916abe91b1c99ad342039abd3f9d3ca0ae",
          "n": 8192,
          "r": 8,
          "p": 1
        },
        "mac": "15863e0239f101fe60f830115044bd8ae1d15124f0d6f4982dd353cf9d9df13e"
      }
    },
    "0x81Df1244dEd6EF44a90a67526E4Ec4497d807F96": {
      "version": 3,
      "id": "992bd18b-7aa7-461e-9e6e-97efc6f6f0df",
      "address": "81df1244ded6ef44a90a67526e4ec4497d807f96",
      "crypto": {
        "ciphertext": "6715634336d9584c8ad56c9f6f1d8f327393a259a2db46e33fe0421a98df6961",
        "cipherparams": {
          "iv": "f1e0ec89b38fdf2f1c37e776af298372"
        },
        "cipher": "aes-128-ctr",
        "kdf": "scrypt",
        "kdfparams": {
          "dklen": 32,
          "salt": "de7ec3ce7852e76de6f279713cd7f2252511b99cd3326aa9b1d6d40ead6c3915",
          "n": 8192,
          "r": 8,
          "p": 1
        },
        "mac": "900646627149dfcba31bccb2ac05191b695adf6ced7df0a115d001ad2d303940"
      }
    }
  }
}
